name: Sync to GitLab and GitCode

on:
  push:
    branches:
      - main
      - dev

jobs:
  push_to_remotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa_gitlab
          echo "${{ secrets.GITCODE_SSH_KEY }}" > ~/.ssh/id_rsa_gitcode
          chmod 600 ~/.ssh/id_rsa_gitlab
          chmod 600 ~/.ssh/id_rsa_gitcode
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa_gitlab
          ssh-add ~/.ssh/id_rsa_gitcode

      - name: Configure Git
        run: |
          git config user.name "KirsminX"
          git config user.email "dino_doge@qq.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab git@gitlab.com:KirsminX/dingmeta.git

      - name: Add GitCode remote
        run: |
          git remote add gitcode git@gitcode.com:KirsminX/dingmeta.git

      - name: Push to GitLab
        run: |
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_gitlab" git push gitlab ${GITHUB_REF#refs/heads/}:refs/heads/${GITHUB_REF#refs/heads/} --force

      - name: Push to GitCode
        run: |
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_gitcode" git push gitcode ${GITHUB_REF#refs/heads/}:refs/heads/${GITHUB_REF#refs/heads/} --force
